/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;
import sample.FSM;
import sample.Finalstate;
import sample.Initstate;
import sample.SamplePackage;
import sample.State;
import sample.Transition;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == SamplePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SamplePackage.FSM:
				sequence_FSM(context, (FSM) semanticObject); 
				return; 
			case SamplePackage.FINALSTATE:
				sequence_Finalstate(context, (Finalstate) semanticObject); 
				return; 
			case SamplePackage.INITSTATE:
				sequence_Initstate(context, (Initstate) semanticObject); 
				return; 
			case SamplePackage.STATE:
				sequence_State(context, (State) semanticObject); 
				return; 
			case SamplePackage.TRANSITION:
				sequence_Transition(context, (Transition) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     FSM returns FSM
	 *
	 * Constraint:
	 *     (name=EString state+=Initstate state+=Finalstate ((state+=State state+=State*) | (transition+=Transition transition+=Transition*))*)
	 */
	protected void sequence_FSM(ISerializationContext context, FSM semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Finalstate returns Finalstate
	 *
	 * Constraint:
	 *     name=EString
	 */
	protected void sequence_Finalstate(ISerializationContext context, Finalstate semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SamplePackage.Literals.STATE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SamplePackage.Literals.STATE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFinalstateAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Initstate returns Initstate
	 *
	 * Constraint:
	 *     name=EString
	 */
	protected void sequence_Initstate(ISerializationContext context, Initstate semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SamplePackage.Literals.STATE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SamplePackage.Literals.STATE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInitstateAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     State returns State
	 *
	 * Constraint:
	 *     name=EString
	 */
	protected void sequence_State(ISerializationContext context, State semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SamplePackage.Literals.STATE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SamplePackage.Literals.STATE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStateAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Transition returns Transition
	 *
	 * Constraint:
	 *     (name=EString stateFrom=[State|EString] StateTo=[State|EString] trigger=EString)
	 */
	protected void sequence_Transition(ISerializationContext context, Transition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SamplePackage.Literals.TRANSITION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SamplePackage.Literals.TRANSITION__NAME));
			if (transientValues.isValueTransient(semanticObject, SamplePackage.Literals.TRANSITION__STATE_FROM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SamplePackage.Literals.TRANSITION__STATE_FROM));
			if (transientValues.isValueTransient(semanticObject, SamplePackage.Literals.TRANSITION__STATE_TO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SamplePackage.Literals.TRANSITION__STATE_TO));
			if (transientValues.isValueTransient(semanticObject, SamplePackage.Literals.TRANSITION__TRIGGER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SamplePackage.Literals.TRANSITION__TRIGGER));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTransitionAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getTransitionAccess().getStateFromStateEStringParserRuleCall_2_0_1(), semanticObject.eGet(SamplePackage.Literals.TRANSITION__STATE_FROM, false));
		feeder.accept(grammarAccess.getTransitionAccess().getStateToStateEStringParserRuleCall_4_0_1(), semanticObject.eGet(SamplePackage.Literals.TRANSITION__STATE_TO, false));
		feeder.accept(grammarAccess.getTransitionAccess().getTriggerEStringParserRuleCall_6_0(), semanticObject.getTrigger());
		feeder.finish();
	}
	
	
}
